# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da965d71bd835c069f81f37c000755d02b015c3dca17ca7c9f9f3da2eaa9441f41a96ceee94be819f771a50382954bb8b1a05b3643b1b70a8d560238703a086

test:
  secret_key_base: c38f80e911638ee9a2e9ce1068ae0729a0341bae4169357415823ed8b86dc6b9d680309cbd223d97c7ed4caf5356c5c806f386e79db99128dbf2ca6cccaeac6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
